website/music/urls.py
from django.conf.urls import url
#from django.urls import path
from . import views

app_name = 'music'

urlpatterns = [
    # /music/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # /music/71(some id)
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
   # url(r'^(?P<album_id>[0-9]+)/$', views.favorite, name='favorite')
    url(r'^album/add/$', views.AlbumCreate.as_view(), name='album-add'),

    #music/album/2/
    url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(),name='album-update'),

    #music/album/2/delete
    url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(),name='album-delete')

]

STATIC_URL = '/static/'

website/website/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/music/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Album(models.Model):
    artist = models.CharField(max_length=200)
    album_title = models.CharField(max_length=200)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title + '-' + self.artist

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=100)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

website/music/views.py
from django.views import generic
from .models import Album
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.core.urlresolvers import reverse_lazy
class IndexView(generic.ListView):
    template_name = 'music/abc.html'
    context_object_name = 'all_albums'

    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
    model = Album                       # Trying to get details of an album
    template_name = 'music/details.html'

class AlbumCreate(CreateView):
    model = Album                       # Trying to create a new album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')

website/music/templates/music/abc.html
<html>
{% extends 'music/main.html' %}
<body>
{% block body %}
    {% if all_albums %}
    <h3> <b>Here are all my albums</b></h3>
    <ul>
        {% for i in all_albums %}
        <li><a href="{% url 'music:detail' i.id %}"> {{ i.album_title }}</a>
        </li>
        <!-- Deleting albums-->
         <form action="{% url 'music:album-delete' i.id %}" method="post" style="display: block;">
             {% csrf_token %}
             <input type="hidden" name="song_id" value="{{ song.id }}" />
             <button type="submit" class="btn btn-danger btn-xs">
                 <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
             </button>
         </form>
         <form action="{% url 'music:album-update' i.id %}" method="post" style="display: block;">
             {% csrf_token %}
             <input type="hidden" name="song_id" value="{{ song.id }}" />
             <button type="submit" class="btn btn-success btn-xs">
                 <span class="glyphicon glyphicon-pencil"></span>
             </button>
         </form>

        {% endfor %}
    </ul>
    {% else %}
    <h3> You don't have any albums</h3>
     {% endif %}
{% endblock %}
</body>
</html>

website/music/templates/music/album_form.html
{% extends 'music/main.html' %}
{% block title %}Add a new album{% endblock %}
{% block album_active %}active{% endblock %}

{% block body %}
  <div class="container-fluid">
      <div class="col-sm-12 col-md-7">
          <div class="panel panel-default">
              <div class="panel panel-body">
                  <form class="form-horizontal" action="" enctype="multipart/form-data" method="post">
                      {% csrf_token %}
                      {% include 'music/form-template.html' %}
                      <div class="form-group">
                          <div class="col-sm-offset-2 col-sm-10">
                              <button type="submit" class="btn btn-success">Submit
                              </button>
                          </div>
                      </div>
                  </form>
              </div>
          </div>
      </div>
  </div>
{% endblock %}

website/music/templates/music/details.html
<!DOCTYPE html>
<html>
{% extends 'music/main.html' %}
<body>
{% load static %}
{% block title %}Album Details{% endblock %}
{% block body %}
    <img src = "{{ album.album_logo.url }}">

    <h2>{{ album.album_title  }}</h2>
    <h3>{{ album.artist  }}</h3>


        {% for song in album.song_set.all %}
            <label>
               {{ song.song_title }}
               {% if song.is_favorite %}
                  <img src="http://i.imgur.com/b9b13Rd.png">
               {% endif %}
                 <form action="#" method="post" style="display: inline;">
                     {% csrf_token %}
                     <input type="hidden" name="song_id" value="{{ song.id }}" />
                     <button type="submit" class="btn btn-danger btn-xs">
                         <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                     </button>
                 </form>
            </label><br>
        {% endfor %}
{% endblock %}

</body>

</html>

website/music/templates/music/form-template.html
{% for field in form %}
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger sm"></span>
    </div>

<label class="control-label col-sm-2">
    {{ field.label_tag }}
</label>
    <div class="col-sm-10">{{ field }} </div>
</div>
{% endfor %}

website/music/templates/music/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Nash{% endblock %}</title>
    <!-- Loads the path to your static file -->
{% load staticfiles %}
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<!--Link to our style.css -->
<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
<!--Google fonts-->
 <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Tangerine">
<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container_fluid">
        <!--Header -->
        <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'music:index' %}"> Nash</a>
        </div>

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <!-- Items-->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="default">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;Albums
                    </a>
                </li>
                <li class="default">
                    <a href="#">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;Songs
                    </a>
                </li>
            </ul>
            <!--Navbar align-right-->
            <div class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'music:album-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add Albums
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout
                    </a>
                </li>
            </div>
        </div>
    </div>

</nav>
{% block body %}
{% endblock %}
</body>
</html>